Fixes missing class key in friend for g++-4.6
The compiler error was:
/home/mblatt/src/dune/release/dumux/dumux/decoupled/2p/diffusion/fvmpfa/lmethod/fvmpfal3dinteractionvolumecontaineradaptive.hh:96:5: error: a class-key must be used when declaring a friend
/home/mblatt/src/dune/release/dumux/dumux/decoupled/2p/diffusion/fvmpfa/lmethod/fvmpfal3dinteractionvolumecontaineradaptive.hh:96:5: error: friend declaration does not name a class or function
make[4]: *** [test_adaptive2p2c2d.o] Fehler 1

Seems like g++-4.6 is having problems with typedefs in a friend
declaration. We now us the original class type for this.


git-svn-id: svn://svn.iws.uni-stuttgart.de/DUMUX/dumux/branches/strip-pdelab@13249 2fb0f335-1f38-0410-981e-8018bf24f1b0